### ISSUE TITLE
No such file or directory @ rb_sysopen //  Errno: ENOENT

### ISSUE THREAD

**Issue by joelmayer** [pjmuller/zendesk-helpcenter-export#1] opened 2016-01-13 11:35 UTC
Export initiates and process until it reaches a certain Article.  

![image](https://cloud.githubusercontent.com/assets/16683920/12293183/64bd9f34-b9fa-11e5-8c59-e3827160301d.png)

I cannot figure out what it is about this article that is causing the failure.  You suspected that maybe the article title starts will a slash (/), but it does not.

![image](https://cloud.githubusercontent.com/assets/16683920/12293171/4ab2aee0-b9fa-11e5-8c73-3a8bed3b85cd.png)

I appreciate your willingness to take a look or provide another hunch :)

**Comment by pjmuller** [comment] 2016-01-14 11:27
Hi Joel,

I added verbose logging to try and find your problem.

Could you run

```
ruby zendesk-helpcenter-export.rb yourzenmail@domain.com YoUrPassWoRd my-zen-subdomain verbose
```

(so an extra 4th "verbose" argument)

**Comment by joelmayer** [comment] 2016-01-14 15:08
Hm, wasn't expecting this.  I get this error with AND without the verbose variable:

![image](https://cloud.githubusercontent.com/assets/16683920/12327813/1d340a3a-bae1-11e5-9180-e10a19075c9c.png)

**Comment by joelmayer** [comment] 2016-01-14 17:14
The new error:

``` ruby
zendesk-helpcenter-export.rb:5: syntax error, unexpected '<'
<!DOCTYPE html>
```

occurs in the old and new versions of the script.

EDIT:  My problem-- didn't save the script correctly when downloading.

**Comment by joelmayer** [comment] 2016-01-18 14:02
Here is the output from the verbose logging:

`````` ruby
STAFF EDUCATION
  MC v7.0
    Staff Only V7.0 01 - Introduction And Navigation For MC V7.0
      buidling dir_path for ["Staff Education", "MC v7.0", "Staff Only V7.0 01 - Introduction And Navigation For MC V7.0"]
      200838243-staff-education/ appended to ./
      201327433-mc-v70/ appended to ./200838243-staff-education/
      204922646-staff-only-v70-01---introduction-and-navigation-for-mc-v70/ appended to ./200838243-staff-education/201327433-mc-v70/
    Staff Only V7.0 02 - System Administration with MC v7.0
      buidling dir_path for ["Staff Education", "MC v7.0", "Staff Only V7.0 02 - System Administration with MC v7.0 "]
      200838243-staff-education/ appended to ./
      201327433-mc-v70/ appended to ./200838243-staff-education/
      205945416-staff-only-v70-02---system-administration-with-mc-v70/ appended to ./200838243-staff-education/201327433-mc-v70/
    Staff Only V7.0 03 - Work Order Management with MC v7.0
      buidling dir_path for ["Staff Education", "MC v7.0", "Staff Only V7.0 03 - Work Order Management with MC v7.0 "]
      200838243-staff-education/ appended to ./
      201327433-mc-v70/ appended to ./200838243-staff-education/
      206276343-staff-only-v70-03---work-order-management-with-mc-v70/ appended to ./200838243-staff-education/201327433-mc-v70/
    Staff Only V7.0 04 - Parts and Purchasing with MC v7.0
      buidling dir_path for ["Staff Education", "MC v7.0", "Staff Only V7.0 04 - Parts and Purchasing with MC v7.0 "]
      200838243-staff-education/ appended to ./
      201327433-mc-v70/ appended to ./200838243-staff-education/
      205945576-staff-only-v70-04---parts-and-purchasing-with-mc-v70/ appended to ./200838243-staff-education/201327433-mc-v70/
    Staff Only V7.0 05 - Reporting with MC v7.0
      buidling dir_path for ["Staff Education", "MC v7.0", "Staff Only V7.0 05 - Reporting with MC v7.0 "]
      200838243-staff-education/ appended to ./
      201327433-mc-v70/ appended to ./200838243-staff-education/
      205945616-staff-only-v70-05---reporting-with-mc-v70/ appended to ./200838243-staff-education/201327433-mc-v70/
    Staff Only V7.0 06 - Asset and PM Management with MC v7.0
      buidling dir_path for ["Staff Education", "MC v7.0", "Staff Only V7.0 06 - Asset and PM Management with MC v7.0 "]
      200838243-staff-education/ appended to ./
      201327433-mc-v70/ appended to ./200838243-staff-education/
      205945626-staff-only-v70-06---asset-and-pm-management-with-mc-v70/ appended to ./200838243-staff-education/201327433-mc-v70/
    Staff Only V7.0 07 - Overview of MC v7.0
      buidling dir_path for ["Staff Education", "MC v7.0", "Staff Only V7.0 07 - Overview of MC v7.0 "]
      200838243-staff-education/ appended to ./
      201327433-mc-v70/ appended to ./200838243-staff-education/
      205945636-staff-only-v70-07---overview-of-mc-v70/ appended to ./200838243-staff-education/201327433-mc-v70/
    Staff Only V7.0 08 - MC Express with MC v7.0
      buidling dir_path for ["Staff Education", "MC v7.0", "Staff Only V7.0 08 - MC Express with MC v7.0"]
      200838243-staff-education/ appended to ./
      201327433-mc-v70/ appended to ./200838243-staff-education/
      205945646-staff-only-v70-08---mc-express-with-mc-v70/ appended to ./200838243-staff-education/201327433-mc-v70/
  System Administration
    Staff Only SA01 - Document and File Management
      buidling dir_path for ["Staff Education", "System Administration", "Staff Only SA01 - Document and File Management "]
      200838243-staff-education/ appended to ./
      201332826-system-administration/ appended to ./200838243-staff-education/
      205966516-staff-only-sa01---document-and-file-management/ appended to ./200838243-staff-education/201332826-system-administration/
    Staff Only SA02 - User and Password Management Techniques
      buidling dir_path for ["Staff Education", "System Administration", "Staff Only SA02 - User and Password Management Techniques"]
      200838243-staff-education/ appended to ./
      201332826-system-administration/ appended to ./200838243-staff-education/
      205966586-staff-only-sa02---user-and-password-management-techniques/ appended to ./200838243-staff-education/201332826-system-administration/
zendesk-helpcenter-export.rb:83:in `initialize': No such file or directory @ rb_sysopen - ./200838243-staff-education/201332826-system-administration/205966586-staff-only-sa02---user-and-password-management-techniques//Staff Only SA02 - User and Password Management Techniques.html (Errno::ENOENT)
        from zendesk-helpcenter-export.rb:83:in `open'
        from zendesk-helpcenter-export.rb:83:in `block (3 levels) in to_html!'
        from zendesk-helpcenter-export.rb:76:in `each'
        from zendesk-helpcenter-export.rb:76:in `block (2 levels) in to_html!'
        from zendesk-helpcenter-export.rb:72:in `each'
        from zendesk-helpcenter-export.rb:72:in `block in to_html!'
        from zendesk-helpcenter-export.rb:68:in `each'
        from zendesk-helpcenter-export.rb:68:in `to_html!'
        from zendesk-helpcenter-export.rb:230:in `<main>'```
``````

**Comment by pjmuller** [comment] 2016-01-23 08:29
Hi there Joel,

sorry for the late response (family health issues). I think it is related to windows having a 260 character max path name. 

Could you try renaming the article to a shorter name? If that works I'll come with another version for windows the generates shorter paths.

**Comment by joelmayer** [comment] 2016-01-26 08:51
I hope that things have turned out okay with your family.  My father is going through something rather dramatic right now.  It's not fun.

Yes, that did it.  It continued past the problem article after I renamed it to something shorter.  Then, 25 articles later, it encountered another one and displayed the same error.  Granted, we do have some long article titles, but I don't think I am going to be able to convince the content team to change their naming strategy.

**Comment by simonvaarning** [comment] 2016-01-28 12:11
Hi, I got the same issue and found out that it was caused by the title having a '/' (forward slash) character in it. When this was removed everything worked as expected.

**Comment by pmorddny** [comment] 2016-02-15 12:12
HI, I got the error when I had a ? in the title. Once I removed it, the export worked. However, I have a lot of articles with question marks in the title.

**Comment by pjmuller** [comment] 2016-03-12 07:04
Hi @simonvaa and @pmorddny , you can now have any special characters in your article names (fixed in pull request #7 )

**Comment by pjmuller** [comment] 2016-03-12 13:50
Hi @joelmayer , you had to wait quite a bit (and I had to refactor quite a lot).
But normally now we have an extra mode where we can export using short directory and filenames.

Use the new way of calling the script (the standard params way) and add the `--compact-file-names` option.

So in full

```
ruby zendesk-helpcenter-export.rb -e yourzenmail@domain.com -p YoUrPassWoRd -d my-zen-subdomain --compact-file-names
```

Let me know if it works!

**Comment by pjmuller** [comment] 2016-04-01 06:06
@joelmayer  As I didn't hear from you, I guess it is fixed. You can reopen an issue if you still need help

**Closed as completed by pjmuller** 2016-04-01 06:06 UTC

**Comment by joelmayer** [comment] 2016-04-01 07:45
I was able to pick this back up just yesterday.  I left it running as I walked away from my desk.  This morning it had completed with no issues.  Thank you!

**Comment by pjmuller** [comment] 2016-04-01 08:39
Super :). Closed it is!
